name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:    
  lint:
    runs-on: ubuntu-latest

    env:
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
          
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run prettier
        run: yarn prettier --write .
      
      - name: Auto commit lint errors
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: applies prettier lint changes
  
