name: Slither Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:    
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          fail-on: high
          node-version: 14